development: &default
  adapter: postgresql
  database: sismo-mx
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  adapter: postgresql
  database: sismo-mx<%= ENV['TEST_ENV_NUMBER'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: 10
