# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2af00ae3321baa55fc4ed95719a53807a6c1122e92d69ebfc96a5bfde3f5786f7660547e5a59967b9cca1626925db3fc49af6232cc51f6f6a0e507dccda9f90d

test:
  secret_key_base: 1e38d0ecdd7eb3ddb2c713810add1e2dce6315802697f98882a82bc9a90e66a19acee8cecd7c358af22c40d7f4f44e9ff9eae5cf23b6f36209766b7ea1009703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
